#include "memhook_interface.h"
#include <sys/syscall.h>
extern MemStampCollector memhookCollector;
extern "C" void memhook_terminal_flush();
extern "C" void heaplens_test_finish() {
    // Synthetic known record generated by each worker on its own TLS.
    memhook_info_t record;
    record.timestamp = 0x484c54455354ULL;
    record.line = syscall(SYS_gettid);
    record.typeofop = true;
    memhookCollector.copy(record);
    memhook_terminal_flush();
}
