var searchData=
[
  ['randomfnv1a',['RandomFNV1A',['../classRandomFNV1A.html',1,'']]],
  ['rcu_5fnode_5ft',['rcu_node_t',['../structrcu__node__t.html',1,'']]],
  ['rdcssdesc_5ft',['rdcssdesc_t',['../structrdcssdesc__t.html',1,'']]],
  ['rebind',['rebind',['../structallocator__interface_1_1rebind.html',1,'allocator_interface&lt; T &gt;::rebind&lt; _Tp1 &gt;'],['../structallocator__new__segregated_1_1rebind.html',1,'allocator_new_segregated&lt; T &gt;::rebind&lt; _Tp1 &gt;'],['../structpool__perthread__and__shared_1_1rebind.html',1,'pool_perthread_and_shared&lt; T, Alloc &gt;::rebind&lt; _Tp1 &gt;'],['../structreclaimer__ebr__token_1_1rebind.html',1,'reclaimer_ebr_token&lt; T, Pool &gt;::rebind&lt; _Tp1 &gt;'],['../structreclaimer__debracap_1_1rebind.html',1,'reclaimer_debracap&lt; T, Pool &gt;::rebind&lt; _Tp1 &gt;'],['../structallocator__once_1_1rebind.html',1,'allocator_once&lt; T &gt;::rebind&lt; _Tp1 &gt;'],['../structreclaimer__ebr__tree_1_1rebind.html',1,'reclaimer_ebr_tree&lt; T, Pool &gt;::rebind&lt; _Tp1 &gt;'],['../structallocator__new_1_1rebind.html',1,'allocator_new&lt; T &gt;::rebind&lt; _Tp1 &gt;'],['../structreclaimer__debra_1_1rebind.html',1,'reclaimer_debra&lt; T, Pool &gt;::rebind&lt; _Tp1 &gt;'],['../structreclaimer__ebr__tree__q_1_1rebind.html',1,'reclaimer_ebr_tree_q&lt; T, Pool &gt;::rebind&lt; _Tp1 &gt;'],['../structreclaimer__hazardptr_1_1rebind.html',1,'reclaimer_hazardptr&lt; T, Pool &gt;::rebind&lt; _Tp1 &gt;'],['../structpool__interface_1_1rebind.html',1,'pool_interface&lt; T, Alloc &gt;::rebind&lt; _Tp1 &gt;'],['../structreclaimer__interface_1_1rebind.html',1,'reclaimer_interface&lt; T, Pool &gt;::rebind&lt; _Tp1 &gt;'],['../structreclaimer__none_1_1rebind.html',1,'reclaimer_none&lt; T, Pool &gt;::rebind&lt; _Tp1 &gt;'],['../structpool__none_1_1rebind.html',1,'pool_none&lt; T, Alloc &gt;::rebind&lt; _Tp1 &gt;'],['../structreclaimer__rcu_1_1rebind.html',1,'reclaimer_rcu&lt; T, Pool &gt;::rebind&lt; _Tp1 &gt;'],['../structallocator__bump_1_1rebind.html',1,'allocator_bump&lt; T &gt;::rebind&lt; _Tp1 &gt;'],['../structpool__numa_1_1rebind.html',1,'pool_numa&lt; T, Alloc &gt;::rebind&lt; _Tp1 &gt;'],['../structreclaimer__debraplus_1_1rebind.html',1,'reclaimer_debraplus&lt; T, Pool &gt;::rebind&lt; _Tp1 &gt;']]],
  ['rebind2',['rebind2',['../structpool__perthread__and__shared_1_1rebind2.html',1,'pool_perthread_and_shared&lt; T, Alloc &gt;::rebind2&lt; _Tp1, _Tp2 &gt;'],['../structreclaimer__interface_1_1rebind2.html',1,'reclaimer_interface&lt; T, Pool &gt;::rebind2&lt; _Tp1, _Tp2 &gt;'],['../structreclaimer__debra_1_1rebind2.html',1,'reclaimer_debra&lt; T, Pool &gt;::rebind2&lt; _Tp1, _Tp2 &gt;'],['../structreclaimer__ebr__tree__q_1_1rebind2.html',1,'reclaimer_ebr_tree_q&lt; T, Pool &gt;::rebind2&lt; _Tp1, _Tp2 &gt;'],['../structreclaimer__ebr__token_1_1rebind2.html',1,'reclaimer_ebr_token&lt; T, Pool &gt;::rebind2&lt; _Tp1, _Tp2 &gt;'],['../structreclaimer__debraplus_1_1rebind2.html',1,'reclaimer_debraplus&lt; T, Pool &gt;::rebind2&lt; _Tp1, _Tp2 &gt;'],['../structreclaimer__ebr__tree_1_1rebind2.html',1,'reclaimer_ebr_tree&lt; T, Pool &gt;::rebind2&lt; _Tp1, _Tp2 &gt;'],['../structreclaimer__hazardptr_1_1rebind2.html',1,'reclaimer_hazardptr&lt; T, Pool &gt;::rebind2&lt; _Tp1, _Tp2 &gt;'],['../structpool__interface_1_1rebind2.html',1,'pool_interface&lt; T, Alloc &gt;::rebind2&lt; _Tp1, _Tp2 &gt;'],['../structreclaimer__none_1_1rebind2.html',1,'reclaimer_none&lt; T, Pool &gt;::rebind2&lt; _Tp1, _Tp2 &gt;'],['../structreclaimer__rcu_1_1rebind2.html',1,'reclaimer_rcu&lt; T, Pool &gt;::rebind2&lt; _Tp1, _Tp2 &gt;'],['../structpool__none_1_1rebind2.html',1,'pool_none&lt; T, Alloc &gt;::rebind2&lt; _Tp1, _Tp2 &gt;'],['../structreclaimer__debracap_1_1rebind2.html',1,'reclaimer_debracap&lt; T, Pool &gt;::rebind2&lt; _Tp1, _Tp2 &gt;'],['../structpool__numa_1_1rebind2.html',1,'pool_numa&lt; T, Alloc &gt;::rebind2&lt; _Tp1, _Tp2 &gt;']]],
  ['rebindalloc',['rebindAlloc',['../structpool__none_1_1rebindAlloc.html',1,'pool_none&lt; T, Alloc &gt;::rebindAlloc&lt; _Tp1 &gt;'],['../structpool__numa_1_1rebindAlloc.html',1,'pool_numa&lt; T, Alloc &gt;::rebindAlloc&lt; _Tp1 &gt;']]],
  ['rebuildoperation',['RebuildOperation',['../structRebuildOperation.html',1,'']]],
  ['reclaimer_5fdebra',['reclaimer_debra',['../classreclaimer__debra.html',1,'']]],
  ['reclaimer_5fdebracap',['reclaimer_debracap',['../classreclaimer__debracap.html',1,'']]],
  ['reclaimer_5fdebraplus',['reclaimer_debraplus',['../classreclaimer__debraplus.html',1,'']]],
  ['reclaimer_5febr_5ftoken',['reclaimer_ebr_token',['../classreclaimer__ebr__token.html',1,'']]],
  ['reclaimer_5febr_5ftree',['reclaimer_ebr_tree',['../classreclaimer__ebr__tree.html',1,'']]],
  ['reclaimer_5febr_5ftree_5fq',['reclaimer_ebr_tree_q',['../classreclaimer__ebr__tree__q.html',1,'']]],
  ['reclaimer_5fhazardptr',['reclaimer_hazardptr',['../classreclaimer__hazardptr.html',1,'']]],
  ['reclaimer_5finterface',['reclaimer_interface',['../classreclaimer__interface.html',1,'']]],
  ['reclaimer_5fnone',['reclaimer_none',['../classreclaimer__none.html',1,'']]],
  ['reclaimer_5frcu',['reclaimer_rcu',['../classreclaimer__rcu.html',1,'']]],
  ['reclamationinfo',['ReclamationInfo',['../classbst__ns_1_1ReclamationInfo.html',1,'bst_ns']]],
  ['record_5fmanager',['record_manager',['../classrecord__manager.html',1,'']]],
  ['record_5fmanager_3c_20reclaim_2c_20alloc_2c_20pool_2c_20recordtypesfirst_2c_20recordtypesrest_2e_2e_2e_20_3e',['record_manager&lt; Reclaim, Alloc, Pool, RecordTypesFirst, RecordTypesRest... &gt;',['../classrecord__manager.html',1,'']]],
  ['record_5fmanager_5fsingle_5ftype',['record_manager_single_type',['../classrecord__manager__single__type.html',1,'']]],
  ['record_5fmanager_5fsingle_5ftype_3c_20first_2c_20reclaim_2c_20alloc_2c_20pool_20_3e',['record_manager_single_type&lt; First, Reclaim, Alloc, Pool &gt;',['../classrecord__manager__single__type.html',1,'']]],
  ['recordmanagerset',['RecordManagerSet',['../classRecordManagerSet.html',1,'']]],
  ['recordmanagerset_3c_20reclaim_2c_20alloc_2c_20pool_2c_20first_2c_20rest_2e_2e_2e_20_3e',['RecordManagerSet&lt; Reclaim, Alloc, Pool, First, Rest... &gt;',['../classRecordManagerSet_3_01Reclaim_00_01Alloc_00_01Pool_00_01First_00_01Rest_8_8_8_01_4.html',1,'']]],
  ['recordmanagerset_3c_20reclaim_2c_20alloc_2c_20pool_2c_20recordtypesfirst_2c_20rest_2e_2e_2e_20_3e',['RecordManagerSet&lt; Reclaim, Alloc, Pool, RecordTypesFirst, Rest... &gt;',['../classRecordManagerSet.html',1,'']]],
  ['recordmanagerset_3c_20reclaim_2c_20alloc_2c_20pool_2c_20rest_2e_2e_2e_20_3e',['RecordManagerSet&lt; Reclaim, Alloc, Pool, Rest... &gt;',['../classRecordManagerSet.html',1,'']]],
  ['recordmanagersetpostpadded',['RecordManagerSetPostPadded',['../classRecordManagerSetPostPadded.html',1,'']]],
  ['recordmanagersetpostpadded_3c_20reclaim_2c_20alloc_2c_20pool_2c_20recordtypesfirst_2c_20recordtypesrest_2e_2e_2e_20_3e',['RecordManagerSetPostPadded&lt; Reclaim, Alloc, Pool, RecordTypesFirst, RecordTypesRest... &gt;',['../classRecordManagerSetPostPadded.html',1,'']]],
  ['recoverymgr',['RecoveryMgr',['../classRecoveryMgr.html',1,'']]],
  ['recoverymgr_3c_20record_5fmanager_20_3e',['RecoveryMgr&lt; record_manager &gt;',['../classRecoveryMgr.html',1,'']]],
  ['recoverymgr_3c_20void_20_2a_3e',['RecoveryMgr&lt; void *&gt;',['../classRecoveryMgr.html',1,'']]],
  ['relocate_5fop_5ft',['relocate_op_t',['../structrelocate__op__t.html',1,'']]],
  ['reportitem',['ReportItem',['../classReportItem.html',1,'']]],
  ['reqentry',['ReqEntry',['../structReqEntry.html',1,'']]],
  ['rlu_5fdata',['rlu_data',['../structrlu__data.html',1,'']]],
  ['rlu_5fobj_5fheader',['rlu_obj_header',['../structrlu__obj__header.html',1,'']]],
  ['rlu_5fthread_5fdata',['rlu_thread_data',['../structrlu__thread__data.html',1,'']]],
  ['rlu_5fws_5fobj_5fheader',['rlu_ws_obj_header',['../structrlu__ws__obj__header.html',1,'']]],
  ['row_5fhekaton',['Row_hekaton',['../classRow__hekaton.html',1,'']]],
  ['row_5flock',['Row_lock',['../classRow__lock.html',1,'']]],
  ['row_5fmvcc',['Row_mvcc',['../classRow__mvcc.html',1,'']]],
  ['row_5focc',['Row_occ',['../classRow__occ.html',1,'']]],
  ['row_5fsilo',['Row_silo',['../classRow__silo.html',1,'']]],
  ['row_5ft',['row_t',['../classrow__t.html',1,'']]],
  ['row_5ftictoc',['Row_tictoc',['../classRow__tictoc.html',1,'']]],
  ['row_5fts',['Row_ts',['../classRow__ts.html',1,'']]],
  ['row_5fvll',['Row_vll',['../classRow__vll.html',1,'']]],
  ['rqprovider',['RQProvider',['../classRQProvider.html',1,'']]],
  ['rqprovider_3c_20k_2c_20v_2c_20bst_5fns_3a_3anode_3c_20k_2c_20v_20_3e_2c_20bst_5fns_3a_3abst_3c_20k_2c_20v_2c_20compare_2c_20recmanager_20_3e_2c_20recmanager_2c_20false_2c_20false_20_3e',['RQProvider&lt; K, V, bst_ns::Node&lt; K, V &gt;, bst_ns::bst&lt; K, V, Compare, RecManager &gt;, RecManager, false, false &gt;',['../classRQProvider.html',1,'']]],
  ['rqprovider_3c_20k_2c_20void_20_2a_2c_20abtree_5fns_3a_3anode_3c_20degree_2c_20k_20_3e_2c_20abtree_5fns_3a_3aabtree_3c_20degree_2c_20k_2c_20compare_2c_20recmanager_20_3e_2c_20recmanager_2c_20false_2c_20false_20_3e',['RQProvider&lt; K, void *, abtree_ns::Node&lt; DEGREE, K &gt;, abtree_ns::abtree&lt; DEGREE, K, Compare, RecManager &gt;, RecManager, false, false &gt;',['../classRQProvider.html',1,'']]],
  ['rqprovider_3c_20k_2c_20void_20_2a_2c_20bslack_5fns_3a_3anode_3c_20degree_2c_20k_20_3e_2c_20bslack_5fns_3a_3abslack_3c_20degree_2c_20k_2c_20compare_2c_20recmanager_20_3e_2c_20recmanager_2c_20false_2c_20false_20_3e',['RQProvider&lt; K, void *, bslack_ns::Node&lt; DEGREE, K &gt;, bslack_ns::bslack&lt; DEGREE, K, Compare, RecManager &gt;, RecManager, false, false &gt;',['../classRQProvider.html',1,'']]],
  ['rwlock',['RWLock',['../classRWLock.html',1,'']]]
];
